---
- name: Create a new AD Forest
  hosts: initial
  gather_facts: no
  tasks:
    - name: Install AD Domain Services
      win_feature:
        name: AD-Domain-Services
        include_management_tools: yes
      when: "'initial' in group_names"

    - name: Create new AD Forest
      win_domain:
        dns_domain_name: "{{ domain_name }}"
        safe_mode_password: "{{ safe_mode_admin_password }}"
        database_path: "{{ database_path }}"
        log_path: "{{ log_path }}"
        sysvol_path: "{{ sysvol_path }}"
        domain_mode: 'WinThreshold'
        forest_mode: 'WinThreshold'
        create_dns_delegation: "{{ dns_delegation }}"
        reboot: true
        force: "{{ force }}"
      when: "'initial' in group_names"
