---
- name: Join Additional Domain Controllers to Domain
  hosts: replicas
  gather_facts: no
  tasks:
    - name: Install AD Domain Services
      win_feature:
        name: AD-Domain-Services
        include_management_tools: yes
      when: "'replicas' in group_names"

    - name: Join domain controller to domain
      win_domain_controller:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "{{ domain_admin_user }}"
        domain_admin_password: "{{ domain_admin_password }}"
        safe_mode_password: "{{ safe_mode_admin_password }}"
        install_dns: true
        state: domain_controller
        
      when: "'replicas' in group_names"
