---
- name: Setup Ansible Control Node on RHEL 9 with Kerberos Support
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      dnf:
        name:
          - python3
          - python3-pip
          - sshpass
          - ansible
          - krb5-workstation
          - krb5-libs
        state: present

